config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :events
  resources :users
  
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date, presence: true
  validates :duration, presence: true, if: :valid_duration_multiple_of_5
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, inclusion: 1..1000
  validates :location, presence: true

  has_many :attendances
  has_many :users, through: :attendances

  has_many :participants, class_name: 'User'
  belongs_to :admin, class_name: 'User'

  private

  def valid_duration_multiple_of_5
    error.add(:duration, 'La Durée est défini par tranche de 5 minutes') if duration && duration % 5 != 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances
  has_many :events, through: :attendances

  has_many :participants, foreign_key: 'participant_id', class_name: 'Event'
  has_many :admins, foreign_key: 'admin_id', class_name: 'Event'

  after_create :welcome_send
  
  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: %i[new create edit update destroy]

    def new
      @event = Event.new
    end

    def index
      @events = Event.all
    end

    def create
    end

    def show
    end

    def params_event
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_admin?, only: %i[edit update destroy]

  def show
    @user = User.find(params[:id])
    @events = Event.find_by admin_id: params[:id]
  end

  def is_admin?
    redirect_to root_path if user_signed_in? && !current_user.is_admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
<div class="px-5 pt-4 alert alert-danger" role="alert">
  <p>Nous n'avons pas réussi à créer l'Event pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with model: @event, class: "form-group", local: true do |f| %>
    <%= f.label :title,'Titre' %>
     <%= f.text_field :title, class: "form-control", placeholder: 'Écris un titre accrocheur'%>
     <br>
     <%= f.label :description,'Description' %>
     <%= f.text_area :description, class: "form-control", rows: 3, placeholder: 'On veux des détails !!!' %>
     <br>
     <div class="form-row">
       <div class="col">
         <%= f.label :location,'Lieux' %>
         <%= f.text_field :location, class: "form-control", rows:1, placeholder: 'Où ?' %>
       </div>
       <div class="col">
       <%= f.label :start_date,'Date' %>
       <%= f.date_field :start_date, class: "form-control",placeholder: 'Quand ?' %>
       </div>
       <div class="col">
       <%= f.label :duration,'Durée' %>
       <%= f.number_field :duration, class: "form-control", rows:1, min:5,step:5,placeholder: 'La Durée ?' %>
       </div>
       <div class="col">
         <%= f.label :price,'Prix' %>
         <%= f.number_field :price, class: "form-control", min:1,max:1000, rows:1,placeholder: 'Les pépètes' %>
       </div>
     </div>
     <br>
     <%= f.submit "Poster", class: "btn btn-primary" %>
   <% end %>

app/views/events/_header.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">

        <%= link_to 'Eventbrite', root_path, class:"navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
            <li class="nav-item">
                <%= link_to "Créer un événement", new_event_path, class:"nav-link"%>
            </li>

    
            <% if user_signed_in? %>
            
            <li class="nav-item">
            <%= link_to "Déconnection", destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Editer le profil", edit_user_registration_path, class:"nav-link"%>
          </li>
    
            <% else %>
                <li class="nav-item">
                <%= link_to "S'inscrire", new_user_registration_path, class:"nav-link"%>
                </li>
        
                <li class="nav-item">
                <%= link_to "Connexion", new_user_session_path, class:"nav-link"%>
                </li>
            <% end %>
    
        </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <br/>
    <br/>
    

app/views/events/index.html.erb
<div class= text-center>
    <h1> Bienvenue sur le site EventBrit ! </h1>
        <p> Pour cette page d'accueil, vous trouverez la liste des évènements organisés à travers toute la France </p
        <% @events %>

        </div>

app/views/events/new.html.erb
<h3 class="card-title text-center m-4">Organiser un nouvel Event</h3>

<div class="container col-8">
<%= render partial: "events/form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Eventbrit</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <%= render 'events/header' %>
    <%= yield %>
    </header>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>

    <footer class= text-left>
      
    </footer>
</html>

app/views/users/_event.html.erb
<div class="col-md-6">
  <div class="card flex-md-row mb-4 box-shadow h-md-250">
    <div class="card-body d-flex flex-column align-items-start">
      <h3 class="mb-0">
        <a class="text-dark" href="<%= event_path(event.id) %>"><%= event.title %></a>
      </h3>
      <div class="mb-1 text-muted"><%= event.start_date %></div>
    
      <a href="<%= event_path(event.id) %>">Plus de détails</a>
    </div>
     </div>
</div>

app/views/users/show.html.erb
<div class="card">
  <h3 class="card-header text-center"><%= @user.first_name %> <%= @user.last_name %></h3>

  <div class="container col-8 p-4">
  <h4 class="card-title text-center"><%= @user.description %></h4>
  <p class="card-body"> 
</p>
  <% if @user == current_user %>
<%= link_to "Modifier son mail", edit_user_registration_path(@user.id), :class=> "btn btn-primary ml-auto"%>
  </div>
   <% end %>
  </div>
<% if @events != nil %>
    <br>
    <h3 class="text-center">Liste des Events</h3>
    <br>
    <%= render @events %>
<% end %>
</div>